<template>
  <div
    style="
      font-family: Minion Pro, Baskerville, Garamond, EB Garamond, Georgia,
        serif;
      font-size: 18px;
      line-height: 1.5;
      max-width: 40em;
      margin: auto;
    "
  >
    <div class="maketitle">
      <h2 class="titleHead">Constants</h2>
      <div class="author"></div>
      <br />
      <div class="date"></div>
    </div>
    <h3>Heat of Combustion</h3>
    <v-row>
      <v-col cols="12" md="6">
        <a href="https://en.wikipedia.org/wiki/Benzoic_acid">Benzoic Acid</a>
      </v-col>
      <v-col cols="12" md="6"> 26,425 J/g </v-col>
    </v-row>

    <v-row>
      <v-col cols="12" md="6">
        <a href="https://www.americanelements.com/iron-wire-7439-89-6"
          >Iron Wire</a
        >
      </v-col>
      <v-col cols="12" md="6"> 5,858 J/g </v-col>
    </v-row>
    <br />
    <v-divider></v-divider>
    <br />
    <h3>
      <a href="https://en.wikipedia.org/wiki/Gas_constant">Gas Constant</a>
    </h3>

    <v-row>
      <v-col cols="12" md="6">
        <a href="https://en.wikipedia.org/wiki/Gas_constant">R</a>
      </v-col>
      <v-col cols="12" md="6"> 8.314 J/mole-K </v-col>
    </v-row>

    <br />
    <v-divider></v-divider>
    <br />
    <h2>Calorimeter Codes</h2>
    The unique calorimeter constant associated with each Parr Oxygen Bomb
    Combustion Calorimeter is generated by using a 32-bit small fast counter
    (sfc32) with a 4-digit seed, namely, the calorimeter code.
    <br /><br />
    This field lets instructors decode the calorimeter code to reveal the
    associated calorimeter constant.
    <v-container
      class="d-flex justify-center"
      style="width: 400px; margin-bottom: 100px"
    >
      <v-col>
        <v-text-field
          v-model="calorimeterCode"
          label="Calorimeter Code"
          type="number"
          outlined
          dense
          clearable
          :rules="rules.calorimeterCode"
        ></v-text-field>
        <v-dialog
          v-model="dialog"
          max-width="290"
          persistent
          hide-overlay
          transition="dialog-bottom-transition"
        >
          <template v-slot:activator="{ props: activatorProps }">
            <v-btn
              color="green"
              :disabled="calorimeterCode.length !== 4"
              v-bind="activatorProps"
              >Instructor Decode
            </v-btn>
          </template>

          <v-card>
            <v-card-title class="headline">Instructor Decode</v-card-title>
            <v-card-text>
              <v-text-field
                v-model="instructorPassword"
                label="Instructor Password"
                outlined
                dense
                clearable
              ></v-text-field>
              <v-btn
                :disabled="checkPass(instructorPassword)"
                color="green"
                @click="showInstructorDecode"
              >
                Decode
              </v-btn>
            </v-card-text>
            <v-card-actions>
              <v-spacer></v-spacer>
              <v-btn color="green" text @click="dialog = false">Close</v-btn>
            </v-card-actions>
          </v-card>
        </v-dialog>
      </v-col>
    </v-container>
  </div>
</template>

<script lang="js">
import { md5 } from "@/ts/md5.js"

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function sfc32(a, b, c, d) {
  return function () {
    a |= 0;
    b |= 0;
    c |= 0;
    d |= 0;
    const t = (((a + b) | 0) + d) | 0;
    d = (d + 1) | 0;
    a = b ^ (b >>> 9);
    b = (c + (c << 3)) | 0;
    c = (c << 21) | (c >>> 11);
    c = (c + t) | 0;
    return (t >>> 0) / 4294967296;
  };
}

export default {
  data() {
    return {
      calorimeterCode: this.$store.getters.getCalorimeterCode === '' ? getRandomInt(1000, 9999).toString() : this.$store.getters.getCalorimeterCode,
      rules: {
        calorimeterCode: [
          (v) => !!v || 'Calorimeter Code is required',
          (v) => (v && v.length === 4) || 'Calorimeter Code must be 4 digits'
        ]
      },
      dialog: false,
      instructorPassword: ''
    }
  },
  methods: {
    showInstructorDecode() {
      let seed_a = parseInt(this.calorimeterCode[0]);
      let seed_b = parseInt(this.calorimeterCode[1]);
      let seed_c = parseInt(this.calorimeterCode[2]);
      let seed_d = parseInt(this.calorimeterCode[3]);
      let rand = sfc32(seed_a, seed_b, seed_c, seed_d);

      for (let i = 0; i < 100; i++) {
        rand();
      }

      let cBomb = 1182 + 600 * rand();
      let cContents = 50;
      let cParts = 150;
      let cWater = 8368 + 8 * rand();

      let cTotal = cBomb + cContents + cParts + cWater;

      alert('Calorimeter Constant: ' + cTotal.toFixed(2) + ' J/K');
    },
    checkPass(pass) {
      return md5(pass) !== '2b268ff28f38deb26abf16dfe4c76d9a';
    }
  },
};
</script>

<style>
div.maketitle {
  text-align: center;
}
h2.titleHead {
  text-align: center;
  margin-block-start: 0.83em;
  margin-block-end: 0.83em;
  margin-inline-start: 0px;
  margin-inline-end: 0px;
}
div.maketitle {
  margin-bottom: 2em;
}
div.author,
div.date {
  text-align: center;
}
div.thanks {
  text-align: left;
  margin-left: 10%;
  font-size: 85%;
  font-style: italic;
}
div.author {
  white-space: nowrap;
}
div.abstract p {
  margin-left: 5%;
  margin-right: 5%;
}
div.abstract {
  width: 100%;
}
.abstracttitle {
  text-align: center;
  margin-bottom: 1em;
}
.titleHead,
.sectionHead,
.subsectionHead,
.textsf {
  font-family: Myriad Pro, Helvetica, Arial, sans-serif;
}
.titleHead,
.sectionHead,
.subsectionHead {
  color: FireBrick;
}
.texttt,
.verb,
.pre {
  font-family: Inconsolata, Consolas, Courier, monospace;
}
.titleHead {
  font-size: 32px;
}
</style>
